// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_support");
	self attach("head_mp_usmc_shaved_head", "", true);
	self setViewmodel("viewhands_mohw_marines");
	self.voice = "american";
}

precache()
{
	precacheModel("body_mp_usmc_support");
	precacheModel("head_mp_usmc_shaved_head");
	precacheModel("viewhands_mohw_marines");
}
