// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_engineer");
	self setViewmodel("viewhands_mohw_marines");
	self.voice = "american";
}

precache()
{
	precacheModel("body_mp_usmc_engineer");
	precacheModel("viewhands_mohw_marines");
}
