// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_specops");
	self attach("head_mp_usmc_tactical_mich_stripes_nomex", "", true);
	self setViewmodel("viewhands_mohw_marines");
	self.voice = "american";
}

precache()
{
	precacheModel("body_mp_usmc_specops");
	precacheModel("head_mp_usmc_tactical_mich_stripes_nomex");
	precacheModel("viewhands_mohw_marines");
}
